# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWin.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGraphicsView, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenuBar, QPushButton,
    QSizePolicy, QSpinBox, QStatusBar, QTextBrowser,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(900, 700)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.Graph_show = QGraphicsView(self.centralwidget)
        self.Graph_show.setObjectName(u"Graph_show")
        self.Graph_show.setGeometry(QRect(20, 370, 861, 211))
        self.Electric_group = QGroupBox(self.centralwidget)
        self.Electric_group.setObjectName(u"Electric_group")
        self.Electric_group.setGeometry(QRect(30, 10, 371, 161))
        self.pole_number_label = QLabel(self.Electric_group)
        self.pole_number_label.setObjectName(u"pole_number_label")
        self.pole_number_label.setGeometry(QRect(90, 30, 81, 21))
        self.pol_distance_label = QLabel(self.Electric_group)
        self.pol_distance_label.setObjectName(u"pol_distance_label")
        self.pol_distance_label.setGeometry(QRect(90, 70, 61, 21))
        self.lineEdit = QLineEdit(self.Electric_group)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(180, 70, 71, 20))
        self.unit_label = QLabel(self.Electric_group)
        self.unit_label.setObjectName(u"unit_label")
        self.unit_label.setGeometry(QRect(220, 70, 54, 20))
        self.File_pushButton = QPushButton(self.Electric_group)
        self.File_pushButton.setObjectName(u"File_pushButton")
        self.File_pushButton.setGeometry(QRect(70, 100, 191, 41))
        self.spinBox = QSpinBox(self.Electric_group)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(180, 30, 71, 22))
        self.Rock_group = QGroupBox(self.centralwidget)
        self.Rock_group.setObjectName(u"Rock_group")
        self.Rock_group.setGeometry(QRect(410, 10, 291, 161))
        self.Rock_set_pushButton = QPushButton(self.Rock_group)
        self.Rock_set_pushButton.setObjectName(u"Rock_set_pushButton")
        self.Rock_set_pushButton.setGeometry(QRect(20, 60, 251, 41))
        self.label_graph = QLabel(self.centralwidget)
        self.label_graph.setObjectName(u"label_graph")
        self.label_graph.setGeometry(QRect(30, 350, 81, 16))
        self.textBrowser_info = QTextBrowser(self.centralwidget)
        self.textBrowser_info.setObjectName(u"textBrowser_info")
        self.textBrowser_info.setGeometry(QRect(20, 600, 861, 61))
        self.label_info = QLabel(self.centralwidget)
        self.label_info.setObjectName(u"label_info")
        self.label_info.setGeometry(QRect(20, 580, 81, 16))
        self.Weight_group = QGroupBox(self.centralwidget)
        self.Weight_group.setObjectName(u"Weight_group")
        self.Weight_group.setGeometry(QRect(30, 190, 611, 151))
        self.Sun_cal_pushButton = QPushButton(self.Weight_group)
        self.Sun_cal_pushButton.setObjectName(u"Sun_cal_pushButton")
        self.Sun_cal_pushButton.setGeometry(QRect(230, 80, 161, 61))
        self.Electric_cal_pushButton = QPushButton(self.Weight_group)
        self.Electric_cal_pushButton.setObjectName(u"Electric_cal_pushButton")
        self.Electric_cal_pushButton.setGeometry(QRect(80, 20, 131, 41))
        self.destroy_depth_cal__pushButton = QPushButton(self.Weight_group)
        self.destroy_depth_cal__pushButton.setObjectName(u"destroy_depth_cal__pushButton")
        self.destroy_depth_cal__pushButton.setGeometry(QRect(420, 20, 131, 41))
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(710, 10, 181, 151))
        self.pushButton_weight = QPushButton(self.groupBox)
        self.pushButton_weight.setObjectName(u"pushButton_weight")
        self.pushButton_weight.setGeometry(QRect(30, 50, 121, 61))
        self.label_info_2 = QLabel(self.centralwidget)
        self.label_info_2.setObjectName(u"label_info_2")
        self.label_info_2.setGeometry(QRect(660, 180, 81, 16))
        self.textBrowser_result = QTextBrowser(self.centralwidget)
        self.textBrowser_result.setObjectName(u"textBrowser_result")
        self.textBrowser_result.setGeometry(QRect(660, 200, 231, 141))
        self.label_info1 = QLabel(self.centralwidget)
        self.label_info1.setObjectName(u"label_info1")
        self.label_info1.setGeometry(QRect(670, 210, 111, 20))
        self.label_info2 = QLabel(self.centralwidget)
        self.label_info2.setObjectName(u"label_info2")
        self.label_info2.setGeometry(QRect(670, 250, 111, 20))
        self.label_info3 = QLabel(self.centralwidget)
        self.label_info3.setObjectName(u"label_info3")
        self.label_info3.setGeometry(QRect(670, 290, 111, 20))
        self.label_value1 = QLabel(self.centralwidget)
        self.label_value1.setObjectName(u"label_value1")
        self.label_value1.setGeometry(QRect(780, 210, 81, 20))
        self.label_value2 = QLabel(self.centralwidget)
        self.label_value2.setObjectName(u"label_value2")
        self.label_value2.setGeometry(QRect(780, 250, 91, 20))
        self.label_value3 = QLabel(self.centralwidget)
        self.label_value3.setObjectName(u"label_value3")
        self.label_value3.setGeometry(QRect(780, 290, 101, 20))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 900, 23))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Electric_group.setTitle(QCoreApplication.translate("MainWindow", u"\u7535\u6cd5\u529f\u80fd\u533a", None))
        self.pole_number_label.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6781\u4e2a\u6570", None))
        self.pol_distance_label.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6781\u8ddd", None))
        self.unit_label.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.File_pushButton.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u6587\u4ef6", None))
        self.Rock_group.setTitle(QCoreApplication.translate("MainWindow", u"\u5ca9\u5c42\u53c2\u6570\u8bbe\u7f6e", None))
        self.Rock_set_pushButton.setText(QCoreApplication.translate("MainWindow", u"\u5ca9\u5c42\u53c2\u6570\u8bbe\u5b9a", None))
        self.label_graph.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u50cf\u663e\u793a\u533a", None))
        self.label_info.setText(QCoreApplication.translate("MainWindow", u"\u4fe1\u606f\u663e\u793a\u754c\u9762", None))
        self.Weight_group.setTitle(QCoreApplication.translate("MainWindow", u"\u8ba1\u7b97\u529f\u80fd\u533a", None))
        self.Sun_cal_pushButton.setText(QCoreApplication.translate("MainWindow", u"\u603b\u8bc4\u4ef7\u6307\u6807\u8ba1\u7b97", None))
        self.Electric_cal_pushButton.setText(QCoreApplication.translate("MainWindow", u"\u8ba1\u7b97\u7535\u6cd5\u8bc4\u4ef7\u6307\u6807", None))
        self.destroy_depth_cal__pushButton.setText(QCoreApplication.translate("MainWindow", u"\u8ba1\u7b97\u7834\u73af\u6df1\u5ea6", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"\u53c2\u6570\u4fee\u6539", None))
        self.pushButton_weight.setText(QCoreApplication.translate("MainWindow", u"\u603b\u8bc4\u4ef7\u6307\u6807\u6743\u91cd\u4fee\u6539", None))
        self.label_info_2.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u679c\u663e\u793a\u754c\u9762", None))
        self.label_info1.setText(QCoreApplication.translate("MainWindow", u"\u7535\u6cd5\u8bc4\u4ef7\u6307\u6807\uff1a", None))
        self.label_info2.setText(QCoreApplication.translate("MainWindow", u"\u9884\u6d4b\u7834\u574f\u6df1\u5ea6\uff1a", None))
        self.label_info3.setText(QCoreApplication.translate("MainWindow", u"\u603b\u8bc4\u4ef7\u6307\u6807\u503c\uff1a", None))
        self.label_value1.setText("")
        self.label_value2.setText("")
        self.label_value3.setText("")
    # retranslateUi

