# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'SubUi.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################
# 岩层参数子界面
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(819, 572)
        self.layer = QLabel(Dialog)
        self.layer.setObjectName(u"layer")
        self.layer.setGeometry(QRect(370, 5, 91, 41))
        self.layer1 = QLabel(Dialog)
        self.layer1.setObjectName(u"layer1")
        self.layer1.setGeometry(QRect(40, 300, 400, 40))
        self.layer.setAlignment(Qt.AlignCenter)

# 各岩层参数设置的groupbox
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(290, 45, 241, 290))

        self.bd = QLabel(Dialog)
        self.bd.setObjectName(u'bd')
        self.bd.setGeometry(QRect(310, 55, 91, 41))
        self.bd.setAlignment(Qt.AlignCenter)
        self.h = QLabel(Dialog)
        self.h.setObjectName(u"h")
        self.h.setGeometry(QRect(310, 95, 91, 41))
        self.h.setAlignment(Qt.AlignCenter)
        self.G = QLabel(Dialog)
        self.G.setObjectName(u"G")
        self.G.setGeometry(QRect(310, 135, 91, 41))
        self.G.setAlignment(Qt.AlignCenter)
        self.cohesion = QLabel(Dialog)
        self.cohesion.setObjectName(u"cohesion")
        self.cohesion.setGeometry(QRect(310, 175, 91, 41))
        self.cohesion.setAlignment(Qt.AlignCenter)
        self.extension = QLabel(Dialog)
        self.extension.setObjectName(u"extension")
        self.extension.setGeometry(QRect(310, 215, 91, 41))
        self.extension.setAlignment(Qt.AlignCenter)
        self.angle = QLabel(Dialog)
        self.angle.setObjectName(u"angle")
        self.angle.setGeometry(QRect(310, 255, 91, 41))
        self.angle.setAlignment(Qt.AlignCenter)
        self.permeability = QLabel(Dialog)
        self.permeability.setObjectName('permeability')
        self.permeability.setGeometry(QRect(310, 295, 91, 41))
        self.permeability.setAlignment(Qt.AlignCenter)

        self.doubleSpinBox_bd = QDoubleSpinBox(Dialog)
        self.doubleSpinBox_bd.setObjectName(u"容重")
        self.doubleSpinBox_bd.setGeometry(QRect(440, 65, 62, 22))
        self.doubleSpinBox_h = QDoubleSpinBox(Dialog)
        self.doubleSpinBox_h.setObjectName(u"层厚")
        self.doubleSpinBox_h.setGeometry(QRect(440, 105, 62, 22))
        self.doubleSpinBox_G = QDoubleSpinBox(Dialog)
        self.doubleSpinBox_G.setObjectName(u"弹性模量")
        self.doubleSpinBox_G.setGeometry(QRect(440, 145, 62, 22))
        self.doubleSpinBox_Rm = QDoubleSpinBox(Dialog)
        self.doubleSpinBox_Rm.setObjectName(u"内聚力")
        self.doubleSpinBox_Rm.setGeometry(QRect(440, 185, 62, 22))
        self.doubleSpinBox_E = QDoubleSpinBox(Dialog)
        self.doubleSpinBox_E.setObjectName(u"抗拉强度")
        self.doubleSpinBox_E.setGeometry(QRect(440, 225, 62, 22))
        self.doubleSpinBox_phi0 = QDoubleSpinBox(Dialog)
        self.doubleSpinBox_phi0.setObjectName(u"内摩擦角")
        self.doubleSpinBox_phi0.setGeometry(QRect(440, 265, 62, 22))
        self.doubleSpinBox_permeability= QDoubleSpinBox(Dialog)
        self.doubleSpinBox_permeability.setObjectName('doublespinBox_permeability')
        self.doubleSpinBox_permeability.setGeometry(QRect(440, 305, 62, 22))
# 通用参数设置groupbox        
        self.groupBox1 = QGroupBox(Dialog)
        self.groupBox1.setObjectName(u"groupbox1")
        self.groupBox1.setGeometry(QRect(40, 45, 241, 260))


        self.coal_thick = QLabel(Dialog)
        self.coal_thick.setObjectName('coal_thick')
        self.coal_thick.setGeometry(QRect(50, 80, 91, 41))
        self.depth = QLabel(Dialog)
        self.depth.setObjectName('depth')
        self.depth.setGeometry(QRect(50, 120, 91, 41))        
        self.stress = QLabel(Dialog)
        self.stress.setObjectName('stress')
        self.stress.setGeometry(QRect(50, 160, 130, 41))
        self.Cm_col = QLabel(Dialog)
        self.Cm_col.setObjectName('Cm_col')
        self.Cm_col.setGeometry(QRect(50, 200, 130, 41))
        self.phi = QLabel(Dialog)
        self.phi.setObjectName('phi')
        self.phi.setGeometry(QRect(50, 240, 150, 41))

        self.doubleSpinBox_thick = QDoubleSpinBox(Dialog)
        self.doubleSpinBox_thick.setObjectName('doublespinBox_coal_thick')
        self.doubleSpinBox_thick.setGeometry(QRect(200, 90, 62, 22))
        self.doubleSpinBox_depth = QDoubleSpinBox(Dialog)
        self.doubleSpinBox_depth.setObjectName('doublespinBox_coal_thick')
        self.doubleSpinBox_depth.setGeometry(QRect(200, 130, 62, 22))        
        self.doubleSpinBox_stress = QDoubleSpinBox(Dialog)
        self.doubleSpinBox_stress.setObjectName('doublespinBox_coal_thick')
        self.doubleSpinBox_stress.setGeometry(QRect(200, 170, 62, 22))
        self.doubleSpinBox_Cm_col = QDoubleSpinBox(Dialog)
        self.doubleSpinBox_Cm_col.setObjectName('doublespinBox_coal_thick')
        self.doubleSpinBox_Cm_col.setGeometry(QRect(200, 210, 62, 22))
        self.doubleSpinBox_phi = QDoubleSpinBox(Dialog)
        self.doubleSpinBox_phi.setObjectName('doublespinBox_coal_thick')
        self.doubleSpinBox_phi.setGeometry(QRect(200, 250, 62, 22))

        self.comboBox = QComboBox(Dialog)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(470, 15, 61, 22))
        self.comboBox.currentIndexChanged.connect(self.Table_resize)
        self.TableWidget = QTableWidget(Dialog)
        self.TableWidget.setObjectName(u"TableWidget")
        self.TableWidget.setGeometry(QRect(40, 340, 751, 201))

        self.doubleSpinBox_permeability.setMaximum(100000)
        self.doubleSpinBox_h.setMaximum(10000)
        self.doubleSpinBox_depth.setMaximum(10000)
        self.doubleSpinBox_E.setMaximum(10000)
        self.doubleSpinBox_G.setMaximum(10000)
        self.doubleSpinBox_bd.setMaximum(10000)
        self.doubleSpinBox_phi0.setMaximum(10000)
        self.doubleSpinBox_Rm.setMaximum(10000)
        self.doubleSpinBox_Cm_col.setMaximum(10000)
        self.doubleSpinBox_stress.setMaximum(10000)
        self.doubleSpinBox_thick.setMaximum(10000)
        self.doubleSpinBox_phi.setMaximum(10000)

        self.btn_add = QPushButton(Dialog)
        self.btn_add.setObjectName(u"btn_add")
        self.btn_add.setGeometry(QRect(630, 75, 111, 31))
        self.btn_del = QPushButton(Dialog)
        self.btn_del.setObjectName(u"btn_del")
        self.btn_del.setGeometry(QRect(630, 125, 111, 31))
        self.btn_save = QPushButton(Dialog)
        self.btn_save.setObjectName(u"btn_save")
        self.btn_save.setGeometry(QRect(630, 175, 111, 31))
        self.btn_return = QPushButton(Dialog)
        self.btn_return.setObjectName(u"btn_return")
        self.btn_return.setGeometry(QRect(630, 225, 111, 31))
        self.btn_clear = QPushButton(Dialog)
        self.btn_clear.setObjectName(u"btn_clear")
        self.btn_clear.setGeometry(QRect(630, 275, 111, 31))
        self.groupBox.raise_()
        self.groupBox1.raise_()
        self.coal_thick.raise_()
        self.doubleSpinBox_thick.raise_()
        self.depth.raise_()
        self.doubleSpinBox_depth.raise_()
        self.stress.raise_()
        self.Cm_col.raise_()
        self.phi.raise_()
        self.doubleSpinBox_Cm_col.raise_()
        self.doubleSpinBox_stress.raise_()
        self.doubleSpinBox_phi.raise_()

        self.layer.raise_()
        self.bd.raise_()
        self.G.raise_()
        self.h.raise_()
        self.cohesion.raise_()
        self.extension.raise_()
        self.angle.raise_()
        self.permeability.raise_()
        self.doubleSpinBox_permeability.raise_()
        self.doubleSpinBox_bd.raise_()
        self.doubleSpinBox_h.raise_()
        self.doubleSpinBox_E.raise_()
        self.doubleSpinBox_Rm.raise_()
        self.doubleSpinBox_G.raise_()
        self.doubleSpinBox_phi0.raise_()
        self.comboBox.raise_()
        self.TableWidget.raise_()
        self.btn_add.raise_()
        self.btn_del.raise_()
        self.btn_save.raise_()
        self.btn_return.raise_()
        self.btn_clear.raise_()




        self.retranslateUi(Dialog)




        QMetaObject.connectSlotsByName(Dialog)

    def Table_resize(self):     #岩层岩性
        layer = self.comboBox.currentIndex()
        self.TableWidget.setRowCount(layer)
        self.TableWidget.setColumnCount(8)
        self.TableWidget.setSelectionMode(QAbstractItemView.SingleSelection)
        self.TableWidget.setHorizontalHeaderLabels(['岩性', '容重/KN/m³', '层厚/m', '弹性模量/Gpa', '内聚力/Mpa', '抗拉强度/Mpa', '内摩擦角/°', '渗透率/mD'])
        self.TableWidget.setEnabled(True)
        self.TableWidget.setRowCount(layer)
        for i in range(0, layer+1):
            self.lithology = QComboBox(self.TableWidget)
            self.lithology.addItems([u"\u6ce5\u5ca9", u"\u9875\u5ca9", u"\u7802\u5ca9"])
            self.TableWidget.setCellWidget(i, 0, self.lithology)

    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Dialog", None))
        self.layer.setText(QCoreApplication.translate("Dialog", u"\u8bbe\u7f6e\u5ca9\u5c42\u6570", None))
        self.layer1.setText(QCoreApplication.translate("Dialog", u'\u5f53\u524d\u672a\u9009\u4e2d\u5c42', None))
        self.G.setText(QCoreApplication.translate("Dialog", u"\u5f39\u6027\u6a21\u91cf/GPa", None))
        self.permeability.setText(QCoreApplication.translate("Dialog", u"\u6e17\u900f\u7387/mD", None))
        self.h.setText(QCoreApplication.translate("Dialog", u"\u5c42\u539a/m", None))
        self.cohesion.setText(QCoreApplication.translate("Dialog", u"\u5185\u805a\u529b/MPa", None))
        self.extension.setText(QCoreApplication.translate("Dialog", u"\u6297\u62c9\u5f3a\u5ea6/MPa", None))
        self.bd.setText(QCoreApplication.translate("Dialog", u"\u5bb9\u91cd/KN/m³", None))
        self.angle.setText(QCoreApplication.translate("Dialog", u"\u5185\u6469\u64e6\u89d2/°", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"\u5ca9\u5c42\u53c2\u6570\u8bbe\u7f6e", None))
        self.groupBox1.setTitle(QCoreApplication.translate("Dialog", u"\u901a\u7528\u53c2\u6570\u8bbe\u7f6e", None))
        self.coal_thick.setText(QCoreApplication.translate("Dialog", u"\u91c7\u539a/m", None))
        self.depth.setText(QCoreApplication.translate("Dialog", u"\u57cb\u6df1/m", None))
        self.stress.setText(QCoreApplication.translate("Dialog", u"\u5e94\u529b\u96c6\u4e2d\u7cfb\u6570(1~5)", None))
        self.Cm_col.setText(QCoreApplication.translate("Dialog", u"\u7164\u5c42\u5185\u805a\u529b/MPa", None))
        self.phi.setText(QCoreApplication.translate("Dialog", u"\u7164\u5c42\u5185\u6469\u64e6\u89d2/°", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("Dialog", u"", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("Dialog", u"1", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("Dialog", u"2", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("Dialog", u"3", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("Dialog", u"4", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("Dialog", u"5", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("Dialog", u"6", None))
        self.comboBox.setItemText(7, QCoreApplication.translate("Dialog", u"7", None))
        self.comboBox.setItemText(8, QCoreApplication.translate("Dialog", u"8", None))
        self.comboBox.setItemText(9, QCoreApplication.translate("Dialog", u"9", None))
        self.comboBox.setItemText(10, QCoreApplication.translate("Dialog", u"10", None))


        self.btn_add.setText(QCoreApplication.translate("Dialog", u"\u6dfb\u52a0", None))
        self.btn_del.setText(QCoreApplication.translate("Dialog", u"\u5220\u9664", None))
        self.btn_save.setText(QCoreApplication.translate("Dialog", u"\u4fdd\u5b58", None))
        self.btn_return.setText(QCoreApplication.translate("Dialog", u"\u8fd8\u539f\u4fdd\u5b58\u53c2\u6570", None))
        self.btn_clear.setText(QCoreApplication.translate("Dialog", u"\u6e05\u9664", None))
    # retranslateUi

